# Use a Python base image
FROM python:3

# Set working directory
WORKDIR /app

# Copy the app files into the container
COPY . .

# Expose the UDP port
EXPOSE 43210/udp

# Command to run the server
CMD ["./bombsquad_server"]
